# Generated by Django 4.2.23 on 2026-02-10 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_worktyperequest_permanent_request'),
        ('leave', '0003_leavetypenew'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRotatingWorkTypeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotating_work_type', models.CharField(choices=[('WFH to WFO', 'WFH to WFO'), ('WFO to WFH', 'WFO to WFH'), ('Dynamic Create', 'Dynamic Create')], max_length=32)),
                ('start_date', models.DateField()),
                ('based_on', models.CharField(choices=[('After', 'After'), ('Weekend', 'Weekend'), ('Monthly', 'Monthly')], max_length=16)),
                ('rotate_after_day', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotating_work_assignments', to='employee.employee')),
            ],
        ),
    ]
