# Generated by Django 4.2.23 on 2026-02-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_employeerotatingworktypeassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavenew',
            name='end_date_breakdown',
            field=models.CharField(choices=[('full_day', 'Full Day'), ('first_half', 'First Half'), ('second_half', 'Second Half')], default='full_day', max_length=20, verbose_name='Start Date Breakdown'),
        ),
    ]
