# Generated by Django 4.2.23 on 2026-02-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_leavenew_end_date_breakdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavenew',
            name='end_date_breakdown',
        ),
    ]
