# Generated by Django 4.2.5 on 2026-04-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('based_on_week', models.CharField(choices=[('ALL', 'All'), ('FIRST', 'First Week'), ('SECOND', 'Second Week'), ('THIRD', 'Third Week'), ('FOURTH', 'Fourth Week'), ('FIFTH', 'Fifth Week')], max_length=10)),
                ('based_on_week_day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('company', models.CharField(max_length=255)),
            ],
        ),
    ]
