# Generated by Django 4.2.23 on 2026-03-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='recruitment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='recruitment.recruitment', verbose_name='Recruitment'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='stage_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.stage', verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='candidatedocument',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.candidate', verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='candidaterating',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_rating', to='recruitment.candidate'),
        ),
        migrations.AlterField(
            model_name='recruitmentsurveyanswer',
            name='recruitment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.recruitment', verbose_name='Recruitment'),
        ),
        migrations.AlterField(
            model_name='rejectedcandidate',
            name='candidate_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_candidate', to='recruitment.candidate', verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='skillzonecandidate',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skillzonecandidate_set', to='recruitment.candidate', verbose_name='Candidate'),
        ),
    ]
