# Generated by Django 4.2.23 on 2026-04-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_candidate_recruitment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='experience'),
        ),
    ]
