# Generated by Django 4.2.23 on 2026-01-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkinformation',
            name='Basic_Salary_text',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='Company_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='Contract_End_Date_text',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='Department_Name_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='Employee_Tag_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='Employee_Type_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='Job_Position_Name_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='Job_Role_Name_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='Joining_Date_text',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='Reporting_Manager_Name_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='Salary_Per_Hour_text',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='Shift_Name_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='Work_Email_text',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='Work_Location_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='Work_Phone_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='Work_Type_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='Basic_Salary_text',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='Company_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='Contract_End_Date_text',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='Department_Name_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='Employee_Tag_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='Employee_Type_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='Job_Position_Name_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='Job_Role_Name_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='Joining_Date_text',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='Reporting_Manager_Name_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='Salary_Per_Hour_text',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='Shift_Name_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='Work_Email_text',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='Work_Location_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='Work_Phone_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='Work_Type_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
