# Generated by Django 4.2.23 on 2026-01-31 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_basic_salary_text_employeeworkinformation_basic_salary_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeworkinformation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historicalemployeeworkinformation',
            name='id',
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='employee_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_work_info', serialize=False, to='employee.employee', verbose_name='Employee'),
        ),
    ]
