# Generated by Django 4.2.23 on 2026-02-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employeeworkinformation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', help_text='Application role of the employee', max_length=10),
        ),
    ]
