# Generated by Django 4.2.23 on 2026-02-09 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_dynamicemailconfiguration_options_and_more'),
        ('employee', '0007_shiftrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTypeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_type_requests', to='employee.employee', verbose_name='Employee')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.worktype', verbose_name='Work Type')),
            ],
        ),
    ]
