# Generated by Django 4.2.23 on 2026-02-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_worktyperequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktyperequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worktyperequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worktyperequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
