# Generated by Django 4.2.23 on 2026-02-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_worktyperequest_description_worktyperequest_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktyperequest',
            name='permanent_request',
            field=models.BooleanField(default=False),
        ),
    ]
