# Generated by Django 4.2.23 on 2026-02-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_employee_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='badge_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
