# Generated by Django 4.2.23 on 2026-02-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_employee_badge_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='employee',
            name='badge_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
