# Generated by Django 4.2.23 on 2026-03-28 00:00

from django.conf import settings
from django.db import migrations
from django.db.models import Q


ADMIN_USER_GROUP_NAME = "Admin User"
EMPLOYEE_USER_GROUP_NAME = "Employee User"


def create_and_sync_managed_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("auth", "User")
    Employee = apps.get_model("employee", "Employee")

    admin_group, _ = Group.objects.get_or_create(name=ADMIN_USER_GROUP_NAME)
    employee_group, _ = Group.objects.get_or_create(name=EMPLOYEE_USER_GROUP_NAME)

    admin_user_ids = set(
        User.objects.filter(Q(is_superuser=True) | Q(is_staff=True)).values_list(
            "id", flat=True
        )
    )
    admin_user_ids.update(
        Employee.objects.filter(role="admin", employee_user_id__isnull=False).values_list(
            "employee_user_id", flat=True
        )
    )

    for user in User.objects.all().iterator():
        if user.id in admin_user_ids:
            user.groups.add(admin_group)
            user.groups.remove(employee_group)
        else:
            user.groups.add(employee_group)
            user.groups.remove(admin_group)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employee", "0013_remove_employee_is_deleted_alter_employee_badge_id"),
    ]

    operations = [
        migrations.RunPython(
            create_and_sync_managed_groups, migrations.RunPython.noop
        ),
    ]
