# Generated by Django 4.2.23 on 2026-02-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_tracking_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Tracking Id'),
        ),
    ]
