# Generated by Django 4.2.23 on 2026-02-12 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_asset_asset_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.assetcategory', verbose_name='Category'),
        ),
    ]
