# Generated by Django 4.2.23 on 2026-02-12 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_asset_asset_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='asset_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.assetcategory', verbose_name='Asset Category'),
        ),
    ]
