# Generated by Django 4.2.23 on 2026-02-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_alter_assetrequest_asset_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_status',
            field=models.CharField(choices=[('In use', 'In Use'), ('Available', 'Available'), ('Not-Available', 'Not-Available')], max_length=40, verbose_name='Status'),
        ),
    ]
