# Generated by Django 4.2.23 on 2026-02-13 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0010_worktyperequest_permanent_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer_type', models.CharField(choices=[('text', 'Text'), ('mcq', 'MCQ'), ('boolean', 'Boolean'), ('rating', 'Rating')], max_length=20)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='performance.questiontemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('objective', models.CharField(choices=[('employee_engagement', 'Employee Engagement'), ('productivity_metrics', 'Productivity Metrics'), ('increase_sales', 'Increase Sales')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('on_track', 'On Track'), ('behind', 'Behind'), ('closed', 'Closed')], default='not_started', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='employee.employee')),
                ('managers', models.ManyToManyField(blank=True, related_name='managed_objectives', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('mom', models.TextField(blank=True, null=True)),
                ('answerable_employees', models.ManyToManyField(blank=True, related_name='meeting_answerables', to='employee.employee')),
                ('employees', models.ManyToManyField(blank=True, related_name='meeting_employees', to='employee.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='performance.objective')),
            ],
        ),
    ]
