# Generated by Django 4.2.23 on 2026-02-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='keyresult',
            name='name',
        ),
        migrations.RemoveField(
            model_name='keyresult',
            name='objective',
        ),
        migrations.AddField(
            model_name='keyresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='keyresult',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in days', null=True),
        ),
        migrations.AddField(
            model_name='keyresult',
            name='progress_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('number', 'Number'), ('usd', 'USD'), ('inr', 'INR'), ('eur', 'EUR')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='keyresult',
            name='target_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyresult',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='keyresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='description',
            field=models.TextField(),
        ),
    ]
