# Generated by Django 4.2.23 on 2026-02-14 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_worktyperequest_permanent_request'),
        ('performance', '0002_alter_keyresult_options_remove_keyresult_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='question_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.questiontemplate'),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_meetings', to='employee.employee'),
        ),
    ]
