# Generated by Django 4.2.23 on 2026-02-16 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_worktyperequest_permanent_request'),
        ('performance', '0005_feedbackanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBonusEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_points', models.IntegerField()),
                ('bonus_category', models.CharField(choices=[('performance', 'Performance'), ('attendance', 'Attendance'), ('referral', 'Referral'), ('project', 'Project Completion')], max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('awarded_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_bonus_records', to='employee.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
