# Generated by Django 4.2.23 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0010_worktyperequest_permanent_request"),
        ("performance", "0006_newbonusemployee"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF to_regclass('performance_objective') IS NOT NULL
                               AND to_regclass('employee_objective') IS NULL THEN
                                ALTER TABLE performance_objective RENAME TO employee_objective;
                            END IF;
                        END $$;
                    """,
                    reverse_sql="""
                        DO $$
                        BEGIN
                            IF to_regclass('employee_objective') IS NOT NULL
                               AND to_regclass('performance_objective') IS NULL THEN
                                ALTER TABLE employee_objective RENAME TO performance_objective;
                            END IF;
                        END $$;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF to_regclass('performance_keyresult') IS NOT NULL
                               AND to_regclass('employee_keyresult') IS NULL THEN
                                ALTER TABLE performance_keyresult RENAME TO employee_keyresult;
                            END IF;
                        END $$;
                    """,
                    reverse_sql="""
                        DO $$
                        BEGIN
                            IF to_regclass('employee_keyresult') IS NOT NULL
                               AND to_regclass('performance_keyresult') IS NULL THEN
                                ALTER TABLE employee_keyresult RENAME TO performance_keyresult;
                            END IF;
                        END $$;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF to_regclass('performance_question') IS NOT NULL
                               AND to_regclass('employee_question') IS NULL THEN
                                ALTER TABLE performance_question RENAME TO employee_question;
                            END IF;
                        END $$;
                    """,
                    reverse_sql="""
                        DO $$
                        BEGIN
                            IF to_regclass('employee_question') IS NOT NULL
                               AND to_regclass('performance_question') IS NULL THEN
                                ALTER TABLE employee_question RENAME TO performance_question;
                            END IF;
                        END $$;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF to_regclass('performance_meeting') IS NOT NULL
                               AND to_regclass('employee_meeting') IS NULL THEN
                                ALTER TABLE performance_meeting RENAME TO employee_meeting;
                            END IF;
                        END $$;
                    """,
                    reverse_sql="""
                        DO $$
                        BEGIN
                            IF to_regclass('employee_meeting') IS NOT NULL
                               AND to_regclass('performance_meeting') IS NULL THEN
                                ALTER TABLE employee_meeting RENAME TO performance_meeting;
                            END IF;
                        END $$;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF to_regclass('performance_feedback') IS NOT NULL
                               AND to_regclass('employee_feedback360') IS NULL THEN
                                ALTER TABLE performance_feedback RENAME TO employee_feedback360;
                            END IF;
                        END $$;
                    """,
                    reverse_sql="""
                        DO $$
                        BEGIN
                            IF to_regclass('employee_feedback360') IS NOT NULL
                               AND to_regclass('performance_feedback') IS NULL THEN
                                ALTER TABLE employee_feedback360 RENAME TO performance_feedback;
                            END IF;
                        END $$;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name="objective",
                    table="employee_objective",
                ),
                migrations.AlterModelTable(
                    name="keyresult",
                    table="employee_keyresult",
                ),
                migrations.AlterModelTable(
                    name="question",
                    table="employee_question",
                ),
                migrations.AlterModelTable(
                    name="meeting",
                    table="employee_meeting",
                ),
                migrations.AlterModelTable(
                    name="feedback",
                    table="employee_feedback360",
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF to_regclass('performance_objective_managers') IS NOT NULL
                       AND to_regclass('employee_objective_managers') IS NULL THEN
                        ALTER TABLE performance_objective_managers
                        RENAME TO employee_objective_managers;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    IF to_regclass('employee_objective_managers') IS NOT NULL
                       AND to_regclass('performance_objective_managers') IS NULL THEN
                        ALTER TABLE employee_objective_managers
                        RENAME TO performance_objective_managers;
                    END IF;
                END $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF to_regclass('performance_meeting_employees') IS NOT NULL
                       AND to_regclass('employee_meeting_employees') IS NULL THEN
                        ALTER TABLE performance_meeting_employees
                        RENAME TO employee_meeting_employees;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    IF to_regclass('employee_meeting_employees') IS NOT NULL
                       AND to_regclass('performance_meeting_employees') IS NULL THEN
                        ALTER TABLE employee_meeting_employees
                        RENAME TO performance_meeting_employees;
                    END IF;
                END $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF to_regclass('performance_meeting_answerable_employees') IS NOT NULL
                       AND to_regclass('employee_meeting_answerable_employees') IS NULL THEN
                        ALTER TABLE performance_meeting_answerable_employees
                        RENAME TO employee_meeting_answerable_employees;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    IF to_regclass('employee_meeting_answerable_employees') IS NOT NULL
                       AND to_regclass('performance_meeting_answerable_employees') IS NULL THEN
                        ALTER TABLE employee_meeting_answerable_employees
                        RENAME TO performance_meeting_answerable_employees;
                    END IF;
                END $$;
            """,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS employee_feedback360_colleagues (
                            id BIGSERIAL PRIMARY KEY,
                            feedback_id BIGINT NOT NULL
                                REFERENCES employee_feedback360(id)
                                DEFERRABLE INITIALLY DEFERRED,
                            employee_id BIGINT NOT NULL
                                REFERENCES employee_employee(id)
                                DEFERRABLE INITIALLY DEFERRED
                        );
                        DO $$
                        BEGIN
                            IF to_regclass('employee_feedback360_colleagues') IS NOT NULL THEN
                                IF EXISTS (
                                    SELECT 1 FROM information_schema.columns
                                    WHERE table_name = 'employee_feedback360_colleagues'
                                      AND column_name = 'feedback_id_id'
                                ) AND NOT EXISTS (
                                    SELECT 1 FROM information_schema.columns
                                    WHERE table_name = 'employee_feedback360_colleagues'
                                      AND column_name = 'feedback_id'
                                ) THEN
                                    ALTER TABLE employee_feedback360_colleagues
                                    RENAME COLUMN feedback_id_id TO feedback_id;
                                END IF;

                                IF EXISTS (
                                    SELECT 1 FROM information_schema.columns
                                    WHERE table_name = 'employee_feedback360_colleagues'
                                      AND column_name = 'employee_id_id'
                                ) AND NOT EXISTS (
                                    SELECT 1 FROM information_schema.columns
                                    WHERE table_name = 'employee_feedback360_colleagues'
                                      AND column_name = 'employee_id'
                                ) THEN
                                    ALTER TABLE employee_feedback360_colleagues
                                    RENAME COLUMN employee_id_id TO employee_id;
                                END IF;

                                IF EXISTS (
                                    SELECT 1 FROM information_schema.columns
                                    WHERE table_name = 'employee_feedback360_colleagues'
                                      AND column_name = 'feedback_id'
                                ) AND EXISTS (
                                    SELECT 1 FROM information_schema.columns
                                    WHERE table_name = 'employee_feedback360_colleagues'
                                      AND column_name = 'employee_id'
                                ) THEN
                                    CREATE UNIQUE INDEX IF NOT EXISTS employee_feedback360_colleagues_feedback_id_employee_id_uniq
                                        ON employee_feedback360_colleagues (feedback_id, employee_id);
                                    CREATE INDEX IF NOT EXISTS employee_feedback360_colleagues_feedback_id_idx
                                        ON employee_feedback360_colleagues (feedback_id);
                                    CREATE INDEX IF NOT EXISTS employee_feedback360_colleagues_employee_id_idx
                                        ON employee_feedback360_colleagues (employee_id);
                                END IF;
                            END IF;
                        END $$;
                    """,
                    reverse_sql="""
                        DROP TABLE IF EXISTS employee_feedback360_colleagues;
                    """,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="feedback",
                    name="colleagues",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="feedback360_colleagues",
                        to="employee.employee",
                    ),
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS employee_feedback360_subordinates (
                            id BIGSERIAL PRIMARY KEY,
                            feedback_id BIGINT NOT NULL
                                REFERENCES employee_feedback360(id)
                                DEFERRABLE INITIALLY DEFERRED,
                            employee_id BIGINT NOT NULL
                                REFERENCES employee_employee(id)
                                DEFERRABLE INITIALLY DEFERRED
                        );
                        DO $$
                        BEGIN
                            IF to_regclass('employee_feedback360_subordinates') IS NOT NULL THEN
                                IF EXISTS (
                                    SELECT 1 FROM information_schema.columns
                                    WHERE table_name = 'employee_feedback360_subordinates'
                                      AND column_name = 'feedback_id_id'
                                ) AND NOT EXISTS (
                                    SELECT 1 FROM information_schema.columns
                                    WHERE table_name = 'employee_feedback360_subordinates'
                                      AND column_name = 'feedback_id'
                                ) THEN
                                    ALTER TABLE employee_feedback360_subordinates
                                    RENAME COLUMN feedback_id_id TO feedback_id;
                                END IF;

                                IF EXISTS (
                                    SELECT 1 FROM information_schema.columns
                                    WHERE table_name = 'employee_feedback360_subordinates'
                                      AND column_name = 'employee_id_id'
                                ) AND NOT EXISTS (
                                    SELECT 1 FROM information_schema.columns
                                    WHERE table_name = 'employee_feedback360_subordinates'
                                      AND column_name = 'employee_id'
                                ) THEN
                                    ALTER TABLE employee_feedback360_subordinates
                                    RENAME COLUMN employee_id_id TO employee_id;
                                END IF;

                                IF EXISTS (
                                    SELECT 1 FROM information_schema.columns
                                    WHERE table_name = 'employee_feedback360_subordinates'
                                      AND column_name = 'feedback_id'
                                ) AND EXISTS (
                                    SELECT 1 FROM information_schema.columns
                                    WHERE table_name = 'employee_feedback360_subordinates'
                                      AND column_name = 'employee_id'
                                ) THEN
                                    CREATE UNIQUE INDEX IF NOT EXISTS employee_feedback360_subordinates_feedback_id_employee_id_uniq
                                        ON employee_feedback360_subordinates (feedback_id, employee_id);
                                    CREATE INDEX IF NOT EXISTS employee_feedback360_subordinates_feedback_id_idx
                                        ON employee_feedback360_subordinates (feedback_id);
                                    CREATE INDEX IF NOT EXISTS employee_feedback360_subordinates_employee_id_idx
                                        ON employee_feedback360_subordinates (employee_id);
                                END IF;
                            END IF;
                        END $$;
                    """,
                    reverse_sql="""
                        DROP TABLE IF EXISTS employee_feedback360_subordinates;
                    """,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="feedback",
                    name="subordinates",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="feedback360_subordinates",
                        to="employee.employee",
                    ),
                )
            ],
        ),
    ]
