# Generated by Django 4.2.23 on 2026-02-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together=set(),
        ),
    ]
