# Generated by Django 4.2.23 on 2026-02-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_merge'),
        ('payroll', '0002_alter_contract_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('employee_id', 'contract_start_date', 'contract_end_date')},
        ),
    ]
