# Generated by Django 4.2.23 on 2026-02-07 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_merge'),
        ('payroll', '0003_alter_contract_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('intern', 'Intern')], max_length=20)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('wage_type', models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily'), ('hourly', 'Hourly')], max_length=20)),
                ('pay_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily'), ('hourly', 'Hourly')], max_length=20)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('department', models.CharField(max_length=100)),
                ('job_position', models.CharField(max_length=100)),
                ('job_role', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('work_type', models.CharField(max_length=100)),
                ('notice_period_days', models.PositiveIntegerField(default=30)),
                ('contract_document', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='employee.employee')),
            ],
        ),
    ]
