# Generated by Django 4.2.23 on 2026-02-07 12:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_merge'),
        ('payroll', '0004_employeecontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('department', models.CharField(max_length=150)),
                ('job_position', models.CharField(max_length=150)),
                ('job_role', models.CharField(max_length=150)),
                ('shift', models.CharField(max_length=150)),
                ('work_type', models.CharField(max_length=150)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('inprocess', 'In Process'), ('confirmed', 'Confirmed'), ('paid', 'Paid')], default='inprocess', max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips_new', to='employee.employee')),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('employee', 'start_date', 'end_date')},
            },
        ),
    ]
