# Generated by Django 4.2.23 on 2026-03-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payslipnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipnew',
            name='basic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='conveyance_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='epf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='esi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='gross_wages',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='lop_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='paid_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='total_working_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payslipnew',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
