# Generated by Django 4.2.23 on 2026-03-12 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0006_payslipnew_basic_payslipnew_conveyance_allowance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslipnew',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payslip New', 'verbose_name_plural': 'Payslips New'},
        ),
        migrations.RemoveField(
            model_name='payslipnew',
            name='generated_at',
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AlterField(
            model_name='payslipnew',
            name='department',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='payslipnew',
            name='job_position',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='payslipnew',
            name='job_role',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='payslipnew',
            name='shift',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='payslipnew',
            name='work_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
