# Generated by Django 4.2.23 on 2026-03-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_alter_payslipnew_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipnew',
            name='deduction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Amount explicitly deducted (passed in payload)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payslipnew',
            name='deduction_description',
            field=models.CharField(blank=True, help_text='Description for the deduction', max_length=255, null=True),
        ),
    ]
