"""
Django settings for horilla project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from os.path import join
from pathlib import Path

import environ
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ["*"]),
    CSRF_TRUSTED_ORIGINS=(
        list,
        [
            "http://localhost:8000",
            "http://192.168.1.192:5173",
            "http://192.168.1.247:5176",
            "http://192.168.1.248:5174",
            "http://192.168.1.109:5173",
            "http://192.168.1.102:5175",    
            "http://13.202.113.121:7098",
        ],
    ),
)

env.read_env(os.path.join(BASE_DIR, ".env"), overwrite=True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")

# Admin access token used by the employee API to allow limited admin visibility via header
# Set via environment variable (recommended) or in settings for local development
EMPLOYEE_ADMIN_ACCESS_TOKEN = env("EMPLOYEE_ADMIN_ACCESS_TOKEN", default=None)

# Application definition

INSTALLED_APPS = [
    "channels",
    "django.contrib.admin",  # Re-enabled for admin access
    "django.contrib.auth",
    "django.contrib.contenttypes",  # Required for permissions and ContentType
    "django.contrib.sessions",
    "django.contrib.messages",  # Required for admin
    "django.contrib.staticfiles",
    "notifications",  # Required by base models
    # "mathfilters",  # Disabled for API-only mode
    "corsheaders",
    "simple_history",
    "django_filters",
    "base",  # Required for models
    "employee",
    "recruitment",
    "recruit",
    "leave",
    "pms",
    "onboarding",
    "asset",
    "attendance",
    "payroll",
    # "widget_tweaks",  # Disabled for API-only mode
    "django_apscheduler",
    "performance",
    "configuration",
]

# Ensure all project apps are always present in every runtime (local/prod/worker).
# This avoids environment-dependent app loading that can cause missing migrations/tables.
REQUIRED_PROJECT_APPS = [
    "accessibility",
    "horilla_audit",
    "horilla_widgets",
    "horilla_crumbs",
    "horilla_documents",
    "horilla_views",
    "horilla_automations",
    "auditlog",
    "biometric",
    "helpdesk",
    "offboarding",
    "horilla_backup",
    "project",
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_yasg",
    "horilla_api",
    "geofencing",
    "facedetection",
]
for app_name in REQUIRED_PROJECT_APPS:
    if app_name not in INSTALLED_APPS:
        INSTALLED_APPS.append(app_name)
INSTALLED_APPS = list(dict.fromkeys(INSTALLED_APPS))
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"

APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "horilla_api.middleware.RejectBasicAuthMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "horilla.urls"

# Templates configuration for Swagger/drf-yasg
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",  # Required for admin
            ],
        },
    },
]

WSGI_APPLICATION = "horilla.wsgi.application"
ASGI_APPLICATION = "horilla.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": env("POSTGRES_HOST"),
        "PORT": env("POSTGRES_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = []
static_dir = BASE_DIR / "static"
if static_dir.exists():
    STATICFILES_DIRS.append(static_dir)

STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


MESSAGE_TAGS = {
    messages.DEBUG: "oh-alert--warning",
    messages.INFO: "oh-alert--info",
    messages.SUCCESS: "oh-alert--success",
    messages.WARNING: "oh-alert--warning",
    messages.ERROR: "oh-alert--danger",
}


CSRF_TRUSTED_ORIGINS = [origin.rstrip("/") for origin in env("CSRF_TRUSTED_ORIGINS")]

LOGIN_URL = "/login"


SIMPLE_HISTORY_REVERT_DISABLED = True

CHANNELS_REDIS_URL = (
    env("CHANNELS_REDIS_URL", default="") or env("REDIS_URL", default="")
).strip()
CHANNELS_REDIS_PREFIX = env("CHANNELS_REDIS_PREFIX", default="horilla")
CHANNELS_LAYER_CAPACITY = env.int("CHANNELS_LAYER_CAPACITY", default=1500)
CHANNELS_LAYER_EXPIRY = env.int("CHANNELS_LAYER_EXPIRY", default=60)

if CHANNELS_REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [CHANNELS_REDIS_URL],
                "prefix": CHANNELS_REDIS_PREFIX,
                "capacity": CHANNELS_LAYER_CAPACITY,
                "expiry": CHANNELS_LAYER_EXPIRY,
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
            "CONFIG": {
                "capacity": CHANNELS_LAYER_CAPACITY,
                "expiry": CHANNELS_LAYER_EXPIRY,
            },
        }
    }


DJANGO_NOTIFICATIONS_CONFIG = {
    "USE_JSONFIELD": True,
    "SOFT_DELETE": True,
    "USE_WATCHED": True,
    "NOTIFICATIONS_STORAGE": "notifications.storage.DatabaseStorage",
    "TEMPLATE": "notifications.html",  # Add this line
}

X_FRAME_OPTIONS = "SAMEORIGIN"

LANGUAGES = (
    ("en", "English (US)"),
    ("de", "Deutsche"),
    ("es", "Español"),
    ("fr", "Français"),
    ("ar", "عربى"),
    ("pt-br", "Português (Brasil)"),
    ("zh-hans", "Simplified Chinese"),
    ("zh-hant", "Traditional Chinese"),
    ("it", "Italian"),
)


LOCALE_PATHS = [
    join(BASE_DIR, "horilla", "locale"),
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = env("TIME_ZONE", default="Asia/Kolkata")

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Production settings
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)
    SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=0)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)
    SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=False)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=False)
    CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=False)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# REST Framework Configuration for API-only mode
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "drf_yasg.renderers.SwaggerUIRenderer",
        "drf_yasg.renderers.ReDocRenderer",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
    },
    "DEFAULT_METADATA_CLASS": "rest_framework.metadata.SimpleMetadata",
    "COERCE_DECIMAL_TO_STRING": False,
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%S%z",
}

# CORS Configuration for React frontend
CORS_ALLOW_ALL_ORIGINS = DEBUG

# Alternatively, if you want to specify allowed origins:
raw_cors_origins = env(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "http://localhost:5173",  # Vite dev server
        "http://localhost:3000",  # React dev server
        "http://localhost:8000",  # Django development
        "http://127.0.0.1:5173",  # Vite dev server
        "http://127.0.0.1:3000",  # React dev server
        "http://127.0.0.1:8000",
        "http://192.168.1.192:5173",
        "http://192.168.1.247:5176",  # Django development
        "http://13.202.113.121",
        "http://13.202.113.121:7098", # Production IP
    ],
    cast=list,
)

CORS_ALLOWED_ORIGINS = [origin.rstrip("/") for origin in raw_cors_origins]

CORS_ALLOW_CREDENTIALS = True  # Allow credentials (cookies, auth headers)

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# Cache Configuration for Dashboard
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "horilla-api-cache",
    }
}

# Email Configuration - Use File-Based Backend for Debugging/Testing
# Emails are saved to disk so you can see what was sent
EMAIL_BACKEND = env("EMAIL_BACKEND", default="base.backends.ConfiguredEmailBackend")
EMAIL_FILE_PATH = os.path.join(BASE_DIR, "emails")
BREVO_API_KEY = env("BREVO_API_KEY", default="")
BREVO_FROM_EMAIL = env("BREVO_FROM_EMAIL", default="noreply@horilla.com")
BREVO_FROM_NAME = env("BREVO_FROM_NAME", default="Ace Technologies")
EMAIL_BRAND_NAME = env("EMAIL_BRAND_NAME", default="Ace Technologies")
EMAIL_SUPPORT_EMAIL = env("EMAIL_SUPPORT_EMAIL", default="admin@acetechnologys.com")
PUBLIC_BACKEND_URL = env(
    "PUBLIC_BACKEND_URL",
    default="" if DEBUG else "http://13.202.113.121",
).rstrip("/")
FRONTEND_APP_URL = env("FRONTEND_APP_URL", default="").rstrip("/")
FRONTEND_RESET_PASSWORD_URL = (
    env("FRONTEND_RESET_PASSWORD_URL", default="")
    or env("Frontend_url", default="")
    or (f"{FRONTEND_APP_URL}/reset-password/:uid/:token" if FRONTEND_APP_URL else "")
)
PASSWORD_RESET_TIMEOUT = env.int("PASSWORD_RESET_TIMEOUT", default=300)
AUTO_CHECK_OUT_TIME = env("AUTO_CHECK_OUT_TIME", default="18:30")

# Alternative backends available:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Print to console
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'     # Send via SMTP

# For production with Brevo:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.brevo.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-smtp-key'

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
}

# Swagger/drf-yasg Configuration
SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT Authorization header using Bearer scheme. Example: Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGc...",
        }
    },
    "USE_SESSION_AUTH": False,
    "DOC_EXPANSION": "none",
}
