# Generated by Django 4.2.23 on 2026-02-05 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_merge'),
        ('project', '0002_projectnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Task Title')),
                ('project_stage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Project Stage')),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('expired', 'Expired')], default='to_do', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.projectnew', verbose_name='Project')),
                ('task_managers', models.ManyToManyField(blank=True, related_name='managed_tasks_new', to='employee.employee', verbose_name='Task Managers')),
                ('task_members', models.ManyToManyField(blank=True, related_name='member_tasks_new', to='employee.employee', verbose_name='Task Members')),
            ],
        ),
    ]
