# Generated by Django 4.2.23 on 2026-02-05 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_merge'),
        ('project', '0003_tasknew'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheetNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('hours_spent', models.DecimalField(decimal_places=2, help_text='Hours spent on task (e.g. 7.50)', max_digits=5, verbose_name='Hours Spent')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='in_progress', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets_new', to='employee.employee', verbose_name='Employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='project.tasknew', verbose_name='Task')),
            ],
        ),
    ]
