# Generated by Django 4.2.23 on 2026-02-06 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_merge'),
        ('project', '0004_timesheetnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetnew',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
