# Generated by Django 4.2.23 on 2026-02-18 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_timesheetnew_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNewStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Stage Title')),
                ('sequence', models.IntegerField(default=0, verbose_name='Sequence Order')),
                ('is_end_stage', models.BooleanField(default=False, verbose_name='Is End Stage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='project.projectnew', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project New Stage',
                'verbose_name_plural': 'Project New Stages',
                'ordering': ['sequence'],
                'unique_together': {('project', 'title')},
            },
        ),
    ]
