# Generated by Django 4.2.23 on 2026-02-18 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_projectnewstage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasknew',
            name='project_stage',
        ),
        migrations.AddField(
            model_name='tasknew',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='project.projectnewstage', verbose_name='Project Stage'),
        ),
    ]
