# Generated by Django 4.2.23 on 2026-02-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_tasknew_project_stage_tasknew_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectnew',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
