# Generated by Django 4.2.23 on 2026-02-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_projectnew_project_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectnew',
            name='project_file',
        ),
        migrations.RemoveField(
            model_name='tasknew',
            name='stage',
        ),
        migrations.AddField(
            model_name='tasknew',
            name='project_stage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project Stage'),
        ),
        migrations.DeleteModel(
            name='ProjectNewStage',
        ),
    ]
