# Generated by Django 4.2.23 on 2026-01-27 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicemailconfiguration',
            options={},
        ),
        migrations.CreateModel(
            name='BrevoEmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='Get your API key from https://app.brevo.com/settings/account/api', max_length=256, verbose_name='Brevo API Key')),
                ('from_email', models.EmailField(default='noreply@horilla.com', max_length=256, verbose_name='From Email Address')),
                ('from_name', models.CharField(default='HR Management', max_length=256, verbose_name='From Name (Display Name)')),
                ('is_active', models.BooleanField(default=True, help_text='Activate/deactivate this configuration', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Email Configuration',
            },
        ),
    ]
