# Generated by Django 4.2.23 on 2026-02-16 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import recruit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0011_employee_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('recruitment_type', models.CharField(choices=[('future_drive', 'Future Drive'), ('recruitment_drive', 'Recruitment Drive')], max_length=50)),
                ('job_position', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('zip_code', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('insider_software', 'Insider Software'), ('application_form', 'Application Form')], max_length=50)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('initial', 'Initial'), ('interview', 'Interview'), ('hired', 'Hired'), ('cancelled', 'Cancelled')], default='applied', max_length=20)),
                ('resume', models.FileField(blank=True, null=True, upload_to=recruit.models.candidate_resume_upload_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_candidates', to='employee.employee')),
            ],
        ),
    ]
