# Generated by Django 4.2.23 on 2026-02-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_skillzone_candidateskill'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidateskill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='candidateskill',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='candidateskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='interviewer',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='CandidateSkill',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.DeleteModel(
            name='SkillZone',
        ),
    ]
