# Generated by Django 4.2.23 on 2026-02-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0013_remove_employee_is_deleted_alter_employee_badge_id'),
        ('recruit', '0005_initial'),
    ]

    # NOTE:
    # 0001..0004 already create these models/tables.
    # Keeping 0006 as a no-op avoids duplicate CREATE TABLE errors
    # on existing databases while preserving migration graph consistency.
    operations = []
