# Generated by Django 4.2.23 on 2026-02-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_early_out',
            field=models.BooleanField(default=False, verbose_name='Is Early Out'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_late_come',
            field=models.BooleanField(default=False, verbose_name='Is Late Come'),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='is_early_out',
            field=models.BooleanField(default=False, verbose_name='Is Early Out'),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='is_late_come',
            field=models.BooleanField(default=False, verbose_name='Is Late Come'),
        ),
    ]
