# Generated by Django 4.2.23 on 2026-02-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_is_early_out_attendance_is_late_come_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_early_out',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_late_come',
        ),
        migrations.RemoveField(
            model_name='historicalattendance',
            name='is_early_out',
        ),
        migrations.RemoveField(
            model_name='historicalattendance',
            name='is_late_come',
        ),
    ]
