# Generated by Django 4.2.23 on 2026-02-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendance_is_early_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceactivity',
            name='is_early_out',
            field=models.BooleanField(default=False, verbose_name='Is Early Out'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='is_late_come',
            field=models.BooleanField(default=False, verbose_name='Is Late Come'),
        ),
    ]
